name: SQLLint

on:
  push:
    branches:
      - build

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    
    - name: Install SQLLint
      run: npm install -g sql-cli
    
    - name: Show installed packages
      run: npm list -g
    - name: Check All files
      run: |
        find . -type f -name "*" -print
    - name: Sql-Lint
      uses: Bidaya0/sql-lint-in-action@v0.0.2
  deploy:
    runs-on: ubuntu-latest 
    needs:
      - lint
    steps:
    - name: Execute SQL File
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_SCHEMA: ${{ secrets.DB_SCHEMA }}
      run: |
        mysql -h $DB_HOST -u $DB_USER --password="$DB_PASSWORD" -D $DB_SCHEMA < glycemia.sql
            
